projectName: mlops-data-modeltraining-prod

pipeline:
    name: mlops-data-modeltraining-pipeline
    github:
      owner: "jagimene"
      repo: "mlops-datapipeline-modeltraining"
      branch: "main"

stack:
    name: mlops-datapipeline-modeltrain-Stack
    tags:
        - key: project
          value: mlops_challenge
        - key: owners
          value: jesusariel.gimenez@gmail.com
        - key: environment
          value: prod

glue:
    bucket_artifact:
      name: artifact
    bucket_data:
      name: data
    database_ml:
      name: ml_db
    crawler_features:
      name: fe_risk
      s3Path: tables/fe_risk
      tablePrefix: null  
      exclusions: null  
      scheduleExpression: null  
      configuration: null